version: '3.4'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: root
    build:
      context : .
      dockerfile: Dockerfile-MySQL.dev
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: 'pictures_db'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql:cached
    ports:
      - "3322:3306"
    env_file: .env.dev
    user: mysql

  web: &app
    container_name: 'pictures_web'
    build:
      context : .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -rf /pictures/tmp/pids/server.pid && bundle exec rake db:create && bundle exec ridgepole -c config/database.yml -E development --apply -f db/Schemafile && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/pictures:cached
    ports:
      - "8080:8080"
    env_file: .env.dev
    privileged: true
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  redis-data:
    driver: local