version: '3.4'
services:
  db:
    image: mysql:5.7
    build:
      context : .
      dockerfile: Dockerfile-MySQL.dev
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: 'pictures_db'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql:cached
    ports:
      - "3312:3306"
    env_file: .env.dev
    user: mysql
  web:
    container_name: 'pictures_web'
    build:
      context : .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -rf /pictures/tmp/pids/server.pid && bundle exec rake db:create && bundle exec ridgepole -c config/database.yml -E development --apply -f db/Schemafile && bundle exec rails s -p 3007 -b '0.0.0.0'"
    volumes:
      - .:/pictures:cached
    ports:
      - "3007:3007"
    env_file: .env.dev
    privileged: true
    depends_on:
      - db

volumes:
  redis-data:
    driver: local