FROM ruby:2.6.3
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash && apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs

RUN gem install bundler
CMD kernel.msgmnb=1048576
ENV APP_HOME /pictures
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
ADD . $APP_HOME
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install